SET 'auto.offset.reset' = 'earliest';

CREATE STREAM CLAIMS WITH (KAFKA_TOPIC='claims', VALUE_FORMAT='AVRO');
CREATE STREAM CLAIMS_REKEYED WITH (VALUE_FORMAT='JSON') AS SELECT ID, DATE, STATE, AMOUNT FROM CLAIMS PARTITION BY ID;
CREATE TABLE CLAIMS_PER_STATE AS SELECT STATE AS STATE, SUM(AMOUNT) AS TOTAL FROM CLAIMS_REKEYED GROUP BY STATE;
